FROM node:20-alpine

WORKDIR /repo

COPY package.json package-lock.json* ./
COPY packages/shared/package.json packages/shared/package.json
COPY apps/web-loja/package.json apps/web-loja/package.json

RUN npm install

COPY packages/shared packages/shared
COPY apps/web-loja apps/web-loja

WORKDIR /repo/apps/web-loja

EXPOSE 3001
CMD ["npm", "run", "dev"]
