FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /repo

COPY package.json package-lock.json* ./
COPY packages/shared/package.json packages/shared/package.json
COPY apps/api/package.json apps/api/package.json

RUN npm install

COPY packages/shared packages/shared
COPY apps/api apps/api

WORKDIR /repo/apps/api
RUN npx prisma generate

EXPOSE 3333
CMD ["npm", "run", "dev"]
